// ─── Job Names ────────────────────────────────────────────────────────────────
export const JobName = {
  SEND_WA_MESSAGE: "send-wa-message",
  SEND_WA_IMAGE: "send-wa-image",
  PROCESS_INCOMING_MESSAGE: "process-incoming-message",
  TRANSCRIBE_VOICE: "transcribe-voice",
  OCR_IMAGE: "ocr-image",
  EXTRACT_TRANSACTION: "extract-transaction",
  CATEGORIZE_TRANSACTION: "categorize-transaction",
  GENERATE_REPORT: "generate-report",
  CONFIRM_TRANSACTION: "confirm-transaction",
  SETUP_RECURRING: "setup-recurring",
  SEND_RECURRING_REMINDER: "send-recurring-reminder",
  EXPIRE_PENDING_CONFIRMATIONS: "expire-pending-confirmations",
  PUBLISH_FINANCIAL_EVENT: "publish-financial-event",
  GENERATE_MONTHLY_REPORT: "generate-monthly-report",
  CHECK_BUDGET: "check-budget",
  PROCESS_BUDGET_COMMAND: "process-budget-command",
  PROCESS_TRANSACTION_COMMAND: "process-transaction-command",
  PROCESS_CUSTOM_COMMAND: "process-custom-command",
  PROCESS_SETTINGS_COMMAND: "process-settings-command",
  ROLLOVER_BUDGETS: "rollover-budgets",
} as const;

// ─── Queue Names ─────────────────────────────────────────────────────────────
export const QueueName = {
  INCOMING_MESSAGE: "incoming-message",
  VOICE_TRANSCRIPTION: "voice-transcription",
  IMAGE_OCR: "image-ocr",
  AI_EXTRACTION: "ai-extraction",
  CATEGORIZATION: "categorization",
  REPORT_GENERATION: "report-generation",
  WA_SENDER: "wa-sender",
  CONFIRMATION: "confirmation",
  RECURRING_SETUP: "recurring-setup",
  RECURRING_REMINDER: "recurring-reminder",
  EVENT_PUBLISHING: "event-publishing",
  MONTHLY_REPORT: "monthly-report",
  BUDGET_CHECK: "budget-check",
  BUDGET_COMMAND: "budget-command",
  TRANSACTION_COMMAND: "transaction-command",
  CUSTOM_COMMAND: "custom-command",
  SETTINGS_COMMAND: "settings-command",
  BUDGET_ROLLOVER: "budget-rollover",
} as const;
